""" attach_audio.py
    INPUT  : final TARGET language audio file(media/translated_audio.mp3) and original video(media/original.mp4) generated by src/combine_audios.py
    OUTPUT : final TRANSLATED video
"""
from moviepy.editor import VideoFileClip, AudioFileClip

class Attach:
    def attach_audio(self, video, audio, lang):
        
        video_clip = VideoFileClip(video)

        audio_clip = AudioFileClip(audio)

        video_clip = video_clip.set_audio(audio_clip)

        output_file = "media/"+lang+"_video.mp4"
        
        video_clip.write_videofile(output_file, codec="libx264")
        
        return output_file
